<a href="https://colab.research.google.com/github/22wh1a04c6/Data-Science-Task/blob/main/Datacleaning_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data cleaning task

In [ ]:
# data cleaning task
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/laptopData.csv")

In [ ]:
# handling null values
df.dropna(inplace=True)
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [ ]:
# remove unnamed col
df=df.drop("Unnamed: 0",axis=1)
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
#drop duplicate rows
df.drop_duplicates(inplace=True)
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1269,Asus,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.2kg,38378.6496
1270,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1271,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1272,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1273,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200

In [ ]:
# handling inches column
df["Inches"]=df["Inches"].replace("?","0")
df["Inches"]=df["Inches"].astype(float)
avg_inch=round(df["Inches"].mean())
df["Inches"]=df["Inches"].replace(0,avg_inch)
df
df["Inches"].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 17.3, 13.5, 12.5, 13. , 18.4, 13.9,
       11.6, 25.6, 35.6, 12.3, 27.3, 24. , 33.5, 15. , 31.6, 17. , 14.1,
       11.3, 10.1])

In [ ]:
# handling memory column
df["Memory"].mode()
df["Memory"]=df["Memory"].replace("?","256GB SSD")
df["Memory"].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '128GB SSD +  1TB HDD', '256GB SSD +  256GB SSD',
       '64GB Flash Storage', '32GB Flash Storage', '256GB SSD +  1TB HDD',
       '256GB SSD +  2TB HDD', '32GB SSD', '2TB HDD', '64GB SSD',
       '1.0TB Hybrid', '512GB SSD +  1TB HDD', '1TB SSD',
       '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '180GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid', '1.0TB HDD',
       '512GB SSD +  1.0TB Hybrid', '256GB SSD +  1.0TB Hybrid'],
      dtype=object)

In [ ]:
#handling weight column
df["Weight"]=df["Weight"].str.strip("kg")
df["Weight"]=df["Weight"].replace("?","0")
df["Weight"]=df["Weight"].astype(float)
avg_weight=round(df["Weight"].mean())
df["Weight"]=df["Weight"].replace(0,avg_weight)

df["Weight"].unique()

array([1.370e+00, 1.340e+00, 1.860e+00, 1.830e+00, 2.100e+00, 2.040e+00,
       1.300e+00, 1.600e+00, 2.200e+00, 9.200e-01, 1.220e+00, 2.500e+00,
       1.620e+00, 1.910e+00, 2.300e+00, 1.350e+00, 1.880e+00, 1.890e+00,
       1.650e+00, 2.710e+00, 1.200e+00, 1.440e+00, 2.800e+00, 2.000e+00,
       2.650e+00, 2.770e+00, 3.200e+00, 1.490e+00, 2.400e+00, 2.130e+00,
       2.430e+00, 1.700e+00, 1.400e+00, 1.800e+00, 1.900e+00, 3.000e+00,
       1.252e+00, 2.700e+00, 2.020e+00, 1.630e+00, 1.960e+00, 1.210e+00,
       2.450e+00, 1.250e+00, 1.500e+00, 2.620e+00, 1.380e+00, 1.580e+00,
       1.850e+00, 1.230e+00, 2.160e+00, 2.360e+00, 7.200e+00, 2.050e+00,
       1.320e+00, 1.750e+00, 9.700e-01, 2.560e+00, 1.480e+00, 1.740e+00,
       1.100e+00, 1.560e+00, 2.030e+00, 1.050e+00, 5.400e+00, 4.400e+00,
       1.290e+00, 1.950e+00, 2.060e+00, 1.120e+00, 3.490e+00, 3.350e+00,
       2.230e+00, 2.900e+00, 4.420e+00, 2.690e+00, 2.370e+00, 4.700e+00,
       3.600e+00, 2.080e+00, 4.300e+00, 1.680e+00, 1.410e+00, 4.140e+00,
       2.180e+00, 2.240e+00, 2.670e+00, 4.100e+00, 2.140e+00, 1.360e+00,
       2.250e+00, 2.150e+00, 2.190e+00, 2.540e+00, 3.420e+00, 5.800e+00,
       1.280e+00, 2.330e+00, 1.450e+00, 2.790e+00, 8.230e+00, 1.260e+00,
       1.840e+00, 2.000e-04, 2.600e+00, 2.260e+00, 3.250e+00, 1.590e+00,
       1.130e+00, 1.420e+00, 1.780e+00, 1.150e+00, 1.270e+00, 1.430e+00,
       2.310e+00, 1.160e+00, 1.640e+00, 2.170e+00, 1.470e+00, 3.780e+00,
       1.790e+00, 9.100e-01, 1.990e+00, 4.330e+00, 1.930e+00, 1.870e+00,
       2.630e+00, 3.400e+00, 3.140e+00, 1.940e+00, 1.240e+00, 4.600e+00,
       4.500e+00, 8.400e+00, 2.730e+00, 1.390e+00, 2.290e+00, 2.590e+00,
       2.940e+00, 1.110e+01, 1.140e+00, 3.800e+00, 6.200e+00, 3.310e+00,
       1.090e+00, 3.210e+00, 1.190e+00, 1.980e+00, 1.170e+00, 4.360e+00,
       1.710e+00, 2.320e+00, 4.200e+00, 1.550e+00, 8.100e-01, 1.180e+00,
       2.720e+00, 1.310e+00, 3.740e+00, 1.760e+00, 1.540e+00, 2.830e+00,
       2.070e+00, 2.380e+00, 3.580e+00, 1.080e+00, 9.800e-01, 2.750e+00,
       2.990e+00, 1.110e+00, 2.090e+00, 4.000e+00, 9.900e-01, 6.900e-01,
       3.520e+00, 2.591e+00, 2.210e+00, 3.300e+00, 2.191e+00, 2.340e+00])

In [ ]:
df.reset_index(inplace=True)
df=df.drop("index",axis=1)
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1239,Asus,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.20,38378.6496
1240,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400
1241,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200
1242,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,12201.1200
1243,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200

In [ ]:
#kaggle task
df=pd.read_csv("Whatsapp_chat.csv")
df=df.drop("Unnamed: 0",axis=1)
df

FileNotFoundError: [Errno 2] No such file or directory: 'Whatsapp_chat.csv'

In [ ]:
df["timestamp"].unique()

In [ ]:
df.drop_duplicates(inplace=True)
df.reset_index(inplace=True)
df=df.drop("index",axis=1)
df

In [ ]:
df=pd.read_csv("swiggy.csv")
df

In [ ]:
df.shape
df.drop_duplicates(inplace=True)
df.shape

In [ ]:
#datacleaning hw task
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/USA_presidents.csv")
df=df.drop("Unnamed: 0",axis=1)
df=df.drop("Unnamed: 0.1",axis=1)
df=df.drop("S.No.",axis=1)
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)
df.reset_index(inplace=True)
df=df.drop("index",axis=1)
df

,president,prior,party,vice,salary,date updated,date created
0,John Quincy Adams,8th United States Secretary of State (1817â...,Democratic- Republican,John C. Calhoun,"$30,0,00",2021-07-14,2012-03-04
1,Andrew Jackson,U.S. Senator ( Class 2 ) from Tennessee ...,Democratic,John C. Calhoun,"$35,0,00",2021-07-14,2012-03-04
2,Martin Van Buren,8th Vice President of the United States,Democratic,Richard Mentor Johnson,"$40,0,00",2021-07-14,2012-03-04
3,William Henry Harrison,United States Minister to Colombia (1828â€“1...,Whig,John Tyler,"$45,0,00",2021-07-14,2012-03-04
4,john tyler,10th Vice President of the United States,"Whig April 4, 1841 â€“ September 13, 1841",Office vacant,"$50,0,00",2021-07-14,2012-03-04
5,James K. Polk,9th Governor of Tennessee (1839â€“1841),Democratic,George M. Dallas,"$55,0,00",2021-07-14,2012-03-04
6,Zachary Taylor,Major General of the 1st Infantry Regiment ...,Whig,Millard Fillmore,"$60,0,00",2021-07-14,2012-03-04
7,Millard Fillmore,12th Vice President of the United States,Whig,Office vacant,"$65,0,00",2021-07-14,2012-03-04
8,Franklin Pierce,Brigadier General of the 9th Infantry Unit...,Democratic,William R. King,"$75,0,00",2021-07-14,2012-03-04
9,James Buchanan,United States Minister to the Court of St J...,Democratic,John C. Breckinridge,"$85,0,00",2021-07-14,2012-03-04
10,Abraham Lincoln,U.S. Representative for Illinois' 7th Distri...,Republican,Hannibal Hamlin,"$95,0,00",2021-07-14,2012-03-04
11,Andrew Johnson,16th Vice President of the United States,Democratic,Office vacant,"$10,5,000",2021-07-14,2012-03-04
12,Ulysses S. Grant,Commanding General of the U.S. Army ( 1864â...,Republican,Schuyler Colfax,"$11,5,000",2021-07-14,2012-03-04
13,Rutherford B. Hayes,29th & 32nd Governor of Ohio (1868â€“1872 &...,Republican,William A. Wheeler,"$12,5,000",2021-07-14,2012-03-04
14,James A. Garfield,U.S. Representative for Ohio's 19th District...,Republican,Chester A. Arthur,"$13,5,000",2021-07-14,2012-03-04
15,Chester A. Arthur,20th Vice President of the United States,Republican,Office vacant,"$14,5,000",2021-07-14,2012-03-04
16,Grover Cleveland,28th Governor of New York (1883â€“1885),Democratic,Thomas A. Hendricks,"$15,5,000",2021-07-14,2012-03-04
17,Benjamin Harrison,U.S. Senator ( Class 1 ) from Indiana (...,Republican,Levi P. Morton,"$16,5,000",2021-07-14,2012-03-04
18,Grover Cleveland,22nd President of the United States (1885â€...,Democratic,Adlai Stevenson,"$17,5,000",2021-07-14,2012-03-04
19,William McKinley,39th Governor of Ohio (1892â€“1896),Republican,Garret Hobart,"$18,5,000",2021-07-14,2012-03-04
20,Theodore Roosevelt,25th Vice President of the United States,Republican,Office vacant,"$19,5,000",2021-07-14,2012-03-04
21,William Howard Taft,42nd United States Secretary of War (1904â€...,Republican,James S. Sherman,"$20,5,000",2021-07-14,2012-03-04
22,Woodrow Wilson,34th Governor of New Jersey (1911â€“1913),Democratic,Thomas R. Marshall,"$22,5,000",2021-07-14,2012-03-04
23,Woodrow Wilson,34th Governor of New Jersey (1911â€“1913),Demorcatic,Thomas R. Marshall,"$22,5,000",2021-07-14,2012-03-04
24,Warren G. Harding,U.S. Senator ( Class 3 ) from Ohio (191...,Republican,Calvin Coolidge,"$23,5,000",2021-07-14,2012-03-04
25,Calvin Coolidge,29th Vice President of the United States,Republican,Office vacant,"$24,5,000",2021-07-14,2012-03-04
26,Herbert Hoover,3rd United States Secretary of Commerce (19...,Republican,Charles Curtis,"$25,5,000",2021-07-14,2012-03-04
27,Franklin D. Roosevelt,44th Governor of New York ( 1929â€“1932 ),Democratic,John Nance Garner,"$26,5,000",2021-07-14,2012-03-04
28,Harry S. Truman,34th Vice President of the United States,Democratic,Office vacant,"$27,5,000",2021-07-14,2012-03-04
29,Dwight D. Eisenhower,Supreme Allied Commander Europe ( 1949â€“1952 ),Republican,Richard Nixon,"$28,5,000",2021-07-14,2012-03-04
30,John F. Kennedy,U.S. Senator ( Class 1 ) from Massachuset...,Democratic,Lyndon B. Johnson,"$29,5,000",2021-07-14,2012-03-04
31,Lyndon B. Johnson,37th Vice President of the United States,Democratic,Office vacant,"$30,5,000",2021-07-14,2012-03-04
32,Richard Nixon,36th Vice President of the United States (1...,Republican,Spiro Agnew,"$31,5,000",2021-07-14,2012-03-04
33,Gerald Ford,40th Vice President of the United States,Republican,Office vacant,"$32,5,000",2021-07-14,2012-03-04
34,Jimmy Carter,76th Governor of Georgia (1971â€“1975),Democratic,Walter Mondale,"$33,5,000",2021-07-14,2012-03-04
35,Ronald Reagan,33rd Governor of California ( 1967â€“1975 ),Republican,George H. W. Bush,"$34,5,000",2021-07-14,2012-03-04
36,George H. W. Bush,43rd Vice President of the United States,Republican,Dan Quayle,"$35,5,000",2021-07-14,2012-03-04
37,Bill Clinton,40th & 42nd Governor of Arkansas (1979â€“19...,Democratic,Al Gore,"$36,5,000",2021-07-14,2012-03-04
38,George W. Bush,46th Governor of Texas ( 1995â€“2000 ),Republican,Dick Cheney,"$37,5,000",2021-07-14,2012-03-04
39,Barack Obama,U.S. Senator ( Class 3 ) from Illinois ...,Democratic,Joe Biden,"$39,5,000",2021-07-14,2020-02-01
40,Donald Trump,Chairman of The Trump Organization ( 1971â...,Republicans,Mike Pence,"$40,5,000",2021-07-14,2020-02-01

In [ ]:
df["date created"].unique()

array(['2012-03-04', '2020-02-01'], dtype=object)